### PR TITLE
Include subtitles into the resulting mp4 file

### PR DESCRIPTION
**Pull request by konstantin-kelemen**
I don't see a reason not to include .srt files into the resulting video file. Was that a planned feature that was omitted?
The offered implementation works perfectly with my LG CX and plays nicely with `-l | --langs` flag.

### CODE REVIEW

**Comment by gacopl** [comment]
Yes it was omitted on purpose all you need is bad subtitle or bad encoding
for mp4box to shit itself. The feature was in alpha but it was removed
because of that

wt., 28 cze 2022, 20:46 użytkownik Konstanin Kelemen <
***@***.***> napisał:

**Comment by konstantin-kelemen** [comment]
Should this be enabled by an additional flag then?

**Comment by gacopl** [comment]
Yes default off and also lang set i am afk but i got ready code somewhere

wt., 28 cze 2022, 20:57 użytkownik Konstanin Kelemen <
***@***.***> napisał:

**Comment by gacopl** [comment]
found it

`
while read i;do
  stream=`echo "$i" | cut -f1 -d\|`
  codec=`echo "$i" | cut -f2 -d\|`
  id=`echo "$i" | cut -f3 -d\|`
  lang=`echo "$i" | cut -f5 -d\|`
  title=`echo "$i" | cut -f6 -d\| | sed 's/ /-/g'`
  mp4opts="-add \"$stream\":lang=$lang:name=\"$title\""
  mp4string+=($mp4opts)
done <<< "$(cat sub.exports | grep srt)"

while read i; do
  mp4opts="-add \"$i\":lang=pol:name='downloaded'"
  mp4string+=($mp4opts)
done <<< $(ls *{pl,pl-sync}.srt)
while read i; do
  if [ "$i" != "" ]; then
    mp4opts="-add \"$i\":lang=eng:name='downloaded'"
    mp4string+=($mp4opts)
  fi
done <<< $(ls *{en,en-sync}.srt)
`

**Comment by gacopl** [comment]
the subtitle support has been added to latest master please test just add -s flag

**Pull request closed without merging**
